name: WDIO E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]
        browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t wdio-telnyx .

      - name: Run tests in Docker
        run: |
          docker run --rm \
          -e BROWSER=${{ matrix.browser }} \
          -e BASE_URL=https://telnyx.com \
          -v ${{ github.workspace }}/reports:/usr/src/app/allure-report \
          wdio-telnyx

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: reports