name: WDIO E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [prod]
        browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t wdio-telnyx .

      - name: Prepare browser-specific reports folder
        run: mkdir -p ${{ github.workspace }}/reports/${{ matrix.browser }}

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e BROWSER=${{ matrix.browser }} \
            -e BASE_URL=https://telnyx.com \
            -v ${{ github.workspace }}/reports/${{ matrix.browser }}:/usr/src/app/allure-report \
            wdio-telnyx \
            sh -c "npx wdio run ./wdio.conf.js && allure generate allure-results --clean -o /usr/src/app/allure-report"

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: reports/${{ matrix.browser }}

      - name: Deploy Allure reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports
          keep_files: true
