name: WDIO E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        platform: [desktop, mobile]

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t wdio-telnyx .

      - name: Prepare folders
        run: |
          mkdir -p ${{ github.workspace }}/results/${{ matrix.platform }}
          mkdir -p ${{ github.workspace }}/reports/${{ matrix.platform }}

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e BROWSER=${{ matrix.browser }} \
            -e PLATFORM=${{ matrix.platform }} \
            -e ALLURE_RESULTS=/usr/src/app/allure-results \
            -v ${{ github.workspace }}/results/${{ matrix.platform }}:/usr/src/app/allure-results \
            wdio-telnyx

      - name: List Allure results
        run: ls -lR results/${{ matrix.platform }}

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure HTML report per platform
        run: |
          npx allure generate results/${{ matrix.platform }} --clean -o reports/${{ matrix.platform }}

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.platform }}
          path: reports/${{ matrix.platform }}

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./reports
          merge-multiple: false

      - name: Create root index.html with buttons for platforms
        run: |
          cat <<EOF > ./reports/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Allure Test Reports</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
              a.button {
                display: inline-block;
                padding: 12px 24px;
                margin: 10px;
                font-size: 18px;
                text-decoration: none;
                color: white;
                background-color: #007bff;
                border-radius: 6px;
              }
              a.button:hover { background-color: #0056b3; }
            </style>
          </head>
          <body>
            <h1>Allure Test Reports</h1>
            <a class="button" href="./desktop/index.html" target="_blank">Desktop</a>
            <a class="button" href="./mobile/index.html" target="_blank">Mobile</a>
          </body>
          </html>
          EOF

      - name: Deploy Allure reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports
          keep_files: false
