name: WDIO E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t wdio-telnyx .

      - name: Prepare browser-specific reports folder
        run: mkdir -p ${{ github.workspace }}/reports/${{ matrix.browser }}

      - name: Check EdgeDriver availability
        if: matrix.browser == 'edge'
        run: |
          if ! docker run --rm wdio-telnyx sh -c "curl -sSf https://msedgedriver.azureedge.net" >/dev/null; then
            echo "EdgeDriver unavailable, fallback to Chrome"
            echo "FALLBACK_BROWSER=chrome" >> $GITHUB_ENV
          fi

      - name: Run tests in Docker
        run: |
          BROWSER=${{ env.FALLBACK_BROWSER || matrix.browser }}
          BROWSER_PROFILE=/tmp/${BROWSER}-profile-$RANDOM-$RANDOM-$RANDOM
          docker run --rm \
            -e BROWSER=$BROWSER \
            -e BROWSER_PROFILE=$BROWSER_PROFILE \
            -e BASE_URL=https://telnyx.com \
            -v ${{ github.workspace }}/reports/${{ matrix.browser }}:/usr/src/app/allure-report \
            wdio-telnyx

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.browser }}
          path: reports/${{ matrix.browser }}

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Create root index.html
        run: |
          cat > ./reports/index.html <<'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Allure Reports</title>
            <style>
              body { font-family: Arial, sans-serif; background: #f5f7fa; margin: 0; padding: 20px; }
              h1 { text-align: center; color: #333; }
              ul { list-style: none; padding: 0; max-width: 400px; margin: 40px auto; }
              li { margin: 15px 0; }
              a { display: flex; align-items: center; padding: 12px 18px; background: white;
                  border-radius: 10px; text-decoration: none; font-size: 18px; color: #333;
                  box-shadow: 0 2px 6px rgba(0,0,0,0.1); transition: 0.2s; }
              a:hover { background: #eef3ff; transform: translateY(-2px); }
            </style>
          </head>
          <body>
            <h1>Allure Reports</h1>
            <ul>
              <li><a href="chrome/index.html">Chrome Report</a></li>
              <li><a href="firefox/index.html">Firefox Report</a></li>
              <li><a href="edge/index.html">Edge Report</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Deploy Allure reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./reports
          keep_files: true
