name: WDIO E2E Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t wdio-telnyx .

      - name: Run WDIO tests in Docker
        run: |
          mkdir -p ${{ github.workspace }}/reports/${{ matrix.browser }}
          echo "Running tests in ${{ matrix.browser }}"
          docker run --rm \
            -e BROWSER=${{ matrix.browser }} \
            -e BASE_URL=https://telnyx.com \
            -v ${{ github.workspace }}/reports/${{ matrix.browser }}:/app/allure-results/${{ matrix.browser }} \
            wdio-telnyx

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: reports/${{ matrix.browser }}

  combine-and-deploy:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure results from all browsers
        uses: actions/download-artifact@v4
        with:
          path: ./allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-11-jre
          npm install -g allure-commandline

      - name: Merge Allure results and generate report
        run: |
          echo "Merging Allure results from browsers..."

          # Create merged-results folder
          mkdir -p ./merged-results

          # Iterate over each browser folder
          for dir in allure-results/*; do
            browser=$(basename "$dir")
            echo "Processing results for $browser"

            # Add environment info for each browser
            echo "Browser=$browser" > "$dir/environment.properties"

            # Copy each browser's results into its own subfolder to avoid overwriting
            mkdir -p ./merged-results/$browser
            cp -r "$dir"/* ./merged-results/$browser/
          done

          # List merged results for debugging
          echo "Merged results structure:"
          ls -R ./merged-results || true

          # Generate Allure report from all merged subfolders
          allure generate ./merged-results/* --clean -o ./allure-report

          # List generated report for debugging
          echo "Generated Allure report:"
          ls -R ./allure-report || true

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
